import type { INodeProperties } from 'n8n-workflow';

export const chatbotDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['chatbot'] } },
		options: [
			{
				name: 'Edit Agent',
				value: 'agentEdit',
				action: 'Create or edit an agent',
				description: 'Create, update, or delete a chatbot agent',
				routing: { request: { method: 'POST', url: '/agent/edit' } },
			},
			{
				name: 'Edit Function',
				value: 'functionEdit',
				action: 'Create or edit a function',
				description: 'Create, update, or delete a chatbot function tool',
				routing: { request: { method: 'POST', url: '/function/edit' } },
			},
			{
				name: 'Edit Knowledge',
				value: 'knowledgeEdit',
				action: 'Create or edit a knowledge entry',
				description: 'Create, update, or delete a knowledge base entry',
				routing: { request: { method: 'POST', url: '/knowledge/edit' } },
			},
			{
				name: 'Edit Quick Reply',
				value: 'quickReplyEdit',
				action: 'Create or edit a quick reply',
				description: 'Create, update, or delete a quick reply shortcut',
				routing: { request: { method: 'POST', url: '/quickreply/edit' } },
			},
			{
				name: 'Edit Trigger',
				value: 'triggerEdit',
				action: 'Create or edit a trigger',
				description: 'Create, update, or delete a chatbot trigger',
				routing: { request: { method: 'POST', url: '/trigger/edit' } },
			},
			{
				name: 'List Agents',
				value: 'agentList',
				action: 'List all agents',
				description: 'Retrieve every chatbot agent configured for the instance',
				routing: { request: { method: 'GET', url: '/agent/list' } },
			},
			{
				name: 'List Functions',
				value: 'functionList',
				action: 'List all functions',
				description: 'Retrieve every chatbot function tool configured for the instance',
				routing: { request: { method: 'GET', url: '/function/list' } },
			},
			{
				name: 'List Knowledge',
				value: 'knowledgeList',
				action: 'List all knowledge entries',
				description: 'Retrieve every knowledge base entry configured for the instance',
				routing: { request: { method: 'GET', url: '/knowledge/list' } },
			},
			{
				name: 'List Quick Replies',
				value: 'quickReplyList',
				action: 'List all quick replies',
				description: 'Retrieve every quick reply shortcut configured for the instance',
				routing: { request: { method: 'GET', url: '/quickreply/showall' } },
			},
			{
				name: 'List Triggers',
				value: 'triggerList',
				action: 'List all triggers',
				description: 'Retrieve every chatbot trigger configured for the instance',
				routing: { request: { method: 'GET', url: '/trigger/list' } },
			},
			{
				name: 'Update Settings',
				value: 'updateSettings',
				action: 'Update chatbot settings',
				description: 'Update the chatbot global settings for the instance',
				routing: { request: { method: 'POST', url: '/instance/updatechatbotsettings' } },
			},
		],
		default: 'updateSettings',
	},

	// ---------- updateSettings ----------
	{
		displayName: 'Settings',
		name: 'settings',
		type: 'collection',
		placeholder: 'Add Setting',
		default: {},
		displayOptions: { show: { resource: ['chatbot'], operation: ['updateSettings'] } },
		options: [
			{
				displayName: 'Chatbot Enabled',
				name: 'chatbot_enabled',
				type: 'boolean',
				default: false,
				description: 'Whether the chatbot is enabled for the instance',
				routing: { send: { type: 'body', property: 'chatbot_enabled' } },
			},
			{
				displayName: 'Default Agent ID',
				name: 'default_agent_id',
				type: 'string',
				default: '',
				description: 'Identifier of the default agent used when no trigger matches',
				routing: { send: { type: 'body', property: 'default_agent_id' } },
			},
			{
				displayName: 'Ignore Groups',
				name: 'chatbot_ignore_groups',
				type: 'boolean',
				default: false,
				description: 'Whether the chatbot should ignore messages from group chats',
				routing: { send: { type: 'body', property: 'chatbot_ignore_groups' } },
			},
			{
				displayName: 'OpenAI API Key',
				name: 'openai_apikey',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'OpenAI API key used by the chatbot agents',
				routing: { send: { type: 'body', property: 'openai_apikey' } },
			},
			{
				displayName: 'Restart After Minutes',
				name: 'chatbot_restart_after_minutes',
				type: 'number',
				default: 0,
				description: 'Minutes of inactivity before the conversation is automatically restarted',
				routing: { send: { type: 'body', property: 'chatbot_restart_after_minutes' } },
			},
			{
				displayName: 'Stop Conversation When',
				name: 'chatbot_stop_conversation_when',
				type: 'string',
				default: '',
				description: 'Keyword or phrase that stops an active conversation',
				routing: { send: { type: 'body', property: 'chatbot_stop_conversation_when' } },
			},
		],
	},

	// ---------- triggerEdit ----------
	{
		displayName: 'Trigger ID',
		name: 'id',
		type: 'string',
		default: '',
		description: 'Identifier of the trigger to edit. Leave empty to create a new trigger.',
		displayOptions: { show: { resource: ['chatbot'], operation: ['triggerEdit'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Delete',
		name: 'delete',
		type: 'boolean',
		default: false,
		description: 'Whether to delete the trigger instead of editing it',
		displayOptions: { show: { resource: ['chatbot'], operation: ['triggerEdit'] } },
		routing: { send: { type: 'body', property: 'delete' } },
	},
	{
		displayName: 'Trigger',
		name: 'trigger',
		type: 'fixedCollection',
		placeholder: 'Add Trigger Data',
		default: {},
		displayOptions: { show: { resource: ['chatbot'], operation: ['triggerEdit'] } },
		options: [
			{
				name: 'values',
				displayName: 'Values',
				values: [
					{
						displayName: 'Agent ID',
						name: 'agent_id',
						type: 'string',
						default: '',
						description: 'Identifier of the agent invoked by the trigger',
					},
					{
						displayName: 'Enabled',
						name: 'enabled',
						type: 'boolean',
						default: true,
						description: 'Whether the trigger is active',
					},
					{
						displayName: 'Keyword',
						name: 'keyword',
						type: 'string',
						default: '',
						description: 'Keyword that activates the trigger when type is keyword',
					},
					{
						displayName: 'Name',
						name: 'name',
						type: 'string',
						default: '',
						description: 'Display name of the trigger',
					},
					{
						displayName: 'Priority',
						name: 'priority',
						type: 'number',
						default: 0,
						description: 'Evaluation priority;	higher values are evaluated first',
					},
					{
						displayName: 'Type',
						name: 'type',
						type: 'options',
						options: [
							{
								name: 'Keyword',
								value: 'keyword',
							},
							{
								name: 'All',
								value: 'all',
							},
							{
								name: 'AI',
								value: 'ai',
							},
						],
						default: 'keyword',
						description: 'Type of trigger evaluation strategy',
					},
			],
			},
		],
	},

	// ---------- agentEdit ----------
	{
		displayName: 'Agent ID',
		name: 'id',
		type: 'string',
		default: '',
		description: 'Identifier of the agent to edit. Leave empty to create a new agent.',
		displayOptions: { show: { resource: ['chatbot'], operation: ['agentEdit'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Delete',
		name: 'delete',
		type: 'boolean',
		default: false,
		description: 'Whether to delete the agent instead of editing it',
		displayOptions: { show: { resource: ['chatbot'], operation: ['agentEdit'] } },
		routing: { send: { type: 'body', property: 'delete' } },
	},
	{
		displayName: 'Agent',
		name: 'agent',
		type: 'fixedCollection',
		placeholder: 'Add Agent Data',
		default: {},
		displayOptions: { show: { resource: ['chatbot'], operation: ['agentEdit'] } },
		options: [
			{
				name: 'values',
				displayName: 'Values',
				values: [
					{
						displayName: 'Enabled',
						name: 'enabled',
						type: 'boolean',
						default: true,
						description: 'Whether the agent is active',
					},
					{
						displayName: 'Instructions',
						name: 'instructions',
						type: 'string',
						default: '',
						description: 'System instructions that define the agent behaviour',
					},
					{
						displayName: 'Max Tokens',
						name: 'max_tokens',
						type: 'number',
						default: 1024,
						description: 'Maximum number of tokens produced in a single response',
					},
					{
						displayName: 'Model',
						name: 'model',
						type: 'string',
						default: 'gpt-4o-mini',
						description: 'Language model identifier used by the agent',
					},
					{
						displayName: 'Name',
						name: 'name',
						type: 'string',
						default: '',
						description: 'Display name of the agent',
					},
					{
						displayName: 'Temperature',
						name: 'temperature',
						type: 'number',
						default: 0.7,
						description: 'Sampling temperature for the language model',
					},
				],
			},
		],
	},

	// ---------- knowledgeEdit ----------
	{
		displayName: 'Knowledge ID',
		name: 'id',
		type: 'string',
		default: '',
		description: 'Identifier of the knowledge entry to edit. Leave empty to create a new entry.',
		displayOptions: { show: { resource: ['chatbot'], operation: ['knowledgeEdit'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Delete',
		name: 'delete',
		type: 'boolean',
		default: false,
		description: 'Whether to delete the knowledge entry instead of editing it',
		displayOptions: { show: { resource: ['chatbot'], operation: ['knowledgeEdit'] } },
		routing: { send: { type: 'body', property: 'delete' } },
	},
	{
		displayName: 'File Type',
		name: 'fileType',
		type: 'options',
		options: [
			{ name: 'Text', value: 'text' },
			{ name: 'URL', value: 'url' },
			{ name: 'File', value: 'file' },
		],
		default: 'text',
		description: 'Type of content stored in the knowledge entry',
		displayOptions: { show: { resource: ['chatbot'], operation: ['knowledgeEdit'] } },
		routing: { send: { type: 'body', property: 'fileType' } },
	},
	{
		displayName: 'Knowledge',
		name: 'knowledge',
		type: 'fixedCollection',
		placeholder: 'Add Knowledge Data',
		default: {},
		displayOptions: { show: { resource: ['chatbot'], operation: ['knowledgeEdit'] } },
		options: [
			{
				name: 'values',
				displayName: 'Values',
				values: [
					{
						displayName: 'Name',
						name: 'name',
						type: 'string',
						default: '',
						description: 'Display name of the knowledge entry',
						routing: { send: { type: 'body', property: 'knowledge.name' } },
					},
					{
						displayName: 'Content',
						name: 'content',
						type: 'string',
						typeOptions: { rows: 6 },
						default: '',
						description: 'Raw text content for the knowledge entry',
						routing: { send: { type: 'body', property: 'knowledge.content' } },
					},
					{
						displayName: 'Agent ID',
						name: 'agent_id',
						type: 'string',
						default: '',
						description: 'Identifier of the agent that owns this knowledge entry',
						routing: { send: { type: 'body', property: 'knowledge.agent_id' } },
					},
					{
						displayName: 'URL',
						name: 'url',
						type: 'string',
						default: '',
						description: 'External URL used as the knowledge source when file type is URL',
						routing: { send: { type: 'body', property: 'knowledge.url' } },
					},
				],
			},
		],
	},

	// ---------- functionEdit ----------
	{
		displayName: 'Function ID',
		name: 'id',
		type: 'string',
		default: '',
		description: 'Identifier of the function to edit. Leave empty to create a new function.',
		displayOptions: { show: { resource: ['chatbot'], operation: ['functionEdit'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Delete',
		name: 'delete',
		type: 'boolean',
		default: false,
		description: 'Whether to delete the function instead of editing it',
		displayOptions: { show: { resource: ['chatbot'], operation: ['functionEdit'] } },
		routing: { send: { type: 'body', property: 'delete' } },
	},
	{
		displayName: 'Function',
		name: 'function',
		type: 'fixedCollection',
		placeholder: 'Add Function Data',
		default: {},
		displayOptions: { show: { resource: ['chatbot'], operation: ['functionEdit'] } },
		options: [
			{
				name: 'values',
				displayName: 'Values',
				values: [
					{
						displayName: 'Agent ID',
						name: 'agent_id',
						type: 'string',
						default: '',
						description: 'Identifier of the agent that owns this function',
					},
					{
						displayName: 'Description',
						name: 'description',
						type: 'string',
						default: '',
						description: 'Description used by the language model to decide when to call the function',
					},
					{
						displayName: 'Enabled',
						name: 'enabled',
						type: 'boolean',
						default: true,
						description: 'Whether the function is available to the agent',
					},
					{
						displayName: 'Name',
						name: 'name',
						type: 'string',
						default: '',
						description: 'Display name of the function tool',
					},
					{
						displayName: 'Parameters',
						name: 'parameters',
						type: 'json',
						default: '{}',
						description: 'JSON schema describing the function parameters',
					},
					{
						displayName: 'Webhook URL',
						name: 'webhook_url',
						type: 'string',
						default: '',
						description: 'URL invoked when the function is executed',
					},
				],
			},
		],
	},

	// ---------- quickReplyEdit ----------
	{
		displayName: 'Quick Reply ID',
		name: 'id',
		type: 'string',
		default: '',
		description: 'Identifier of the quick reply to edit. Leave empty to create a new entry.',
		displayOptions: { show: { resource: ['chatbot'], operation: ['quickReplyEdit'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Delete',
		name: 'delete',
		type: 'boolean',
		default: false,
		description: 'Whether to delete the quick reply instead of editing it',
		displayOptions: { show: { resource: ['chatbot'], operation: ['quickReplyEdit'] } },
		routing: { send: { type: 'body', property: 'delete' } },
	},
	{
		displayName: 'Shortcut',
		name: 'shortCut',
		type: 'string',
		default: '',
		description: 'Shortcut text that triggers the quick reply',
		displayOptions: { show: { resource: ['chatbot'], operation: ['quickReplyEdit'] } },
		routing: { send: { type: 'body', property: 'shortCut' } },
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		options: [
			{ name: 'Audio', value: 'audio' },
			{ name: 'Document', value: 'document' },
			{ name: 'Image', value: 'image' },
			{ name: 'Text', value: 'text' },
			{ name: 'Video', value: 'video' },
		],
		default: 'text',
		description: 'Media type produced by the quick reply',
		displayOptions: { show: { resource: ['chatbot'], operation: ['quickReplyEdit'] } },
		routing: { send: { type: 'body', property: 'type' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		description: 'Text content of the quick reply or media caption',
		displayOptions: { show: { resource: ['chatbot'], operation: ['quickReplyEdit'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		displayName: 'File',
		name: 'file',
		type: 'string',
		default: '',
		description: 'URL or base64 payload of the media file when type is not text',
		displayOptions: { show: { resource: ['chatbot'], operation: ['quickReplyEdit'] } },
		routing: { send: { type: 'body', property: 'file' } },
	},
	{
		displayName: 'Document Name',
		name: 'docName',
		type: 'string',
		default: '',
		description: 'File name displayed when the quick reply sends a document',
		displayOptions: { show: { resource: ['chatbot'], operation: ['quickReplyEdit'] } },
		routing: { send: { type: 'body', property: 'docName' } },
	},
];
