import type { INodeProperties } from 'n8n-workflow';
import { sendAdditionalFields } from './shared';

/**
 * Message resource — covers all /send/* and /message/* endpoints of uazapiGO V2.
 */
export const messageDescription: INodeProperties[] = [
	// ============================================================
	// Operation selector
	// ============================================================
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['message'] } },
		default: 'sendText',
		options: [
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a message',
				description: 'Delete a previously sent message',
				routing: { request: { method: 'POST', url: '/message/delete' } },
			},
			{
				name: 'Download Media',
				value: 'download',
				action: 'Download media from a message',
				description: 'Download or transcribe media attached to a message',
				routing: { request: { method: 'POST', url: '/message/download' } },
			},
			{
				name: 'Edit',
				value: 'edit',
				action: 'Edit a message',
				description: 'Edit the text of a previously sent message',
				routing: { request: { method: 'POST', url: '/message/edit' } },
			},
			{
				name: 'Find',
				value: 'find',
				action: 'Find messages',
				description: 'Search stored messages by filters',
				routing: { request: { method: 'POST', url: '/message/find' } },
			},
			{
				name: 'Mark As Read',
				value: 'markAsRead',
				action: 'Mark messages as read',
				description: 'Mark one or more messages as read',
				routing: { request: { method: 'POST', url: '/message/markread' } },
			},
			{
				name: 'React',
				value: 'react',
				action: 'React to a message',
				description: 'Send an emoji reaction to a message',
				routing: { request: { method: 'POST', url: '/message/react' } },
			},
			{
				name: 'Send Carousel',
				value: 'sendCarousel',
				action: 'Send a carousel message',
				description: 'Send a carousel with multiple cards',
				routing: { request: { method: 'POST', url: '/send/carousel' } },
			},
			{
				name: 'Send Contact',
				value: 'sendContact',
				action: 'Send a contact card',
				description: 'Send a vCard contact',
				routing: { request: { method: 'POST', url: '/send/contact' } },
			},
			{
				name: 'Send Location',
				value: 'sendLocation',
				action: 'Send a location',
				description: 'Send a geographic location',
				routing: { request: { method: 'POST', url: '/send/location' } },
			},
			{
				name: 'Send Location Request',
				value: 'sendLocationRequest',
				action: 'Send a location request button',
				description: 'Send a button that requests the recipient to share their location',
				routing: { request: { method: 'POST', url: '/send/location-button' } },
			},
			{
				name: 'Send Media',
				value: 'sendMedia',
				action: 'Send a media message',
				description: 'Send an image, video, document, audio, sticker, or voice note',
				routing: { request: { method: 'POST', url: '/send/media' } },
			},
			{
				name: 'Send Menu',
				value: 'sendMenu',
				action: 'Send a menu message',
				description: 'Send an interactive menu (button, list, poll, or carousel)',
				routing: { request: { method: 'POST', url: '/send/menu' } },
			},
			{
				name: 'Send Payment Request',
				value: 'sendPaymentRequest',
				action: 'Send a payment request',
				description: 'Send a PIX or boleto payment request',
				routing: { request: { method: 'POST', url: '/send/request-payment' } },
			},
			{
				name: 'Send PIX Button',
				value: 'sendPixButton',
				action: 'Send a PIX button',
				description: 'Send a quick PIX key button',
				routing: { request: { method: 'POST', url: '/send/pix-button' } },
			},
			{
				name: 'Send Presence In Chat',
				value: 'sendPresenceInChat',
				action: 'Send presence in chat',
				description: 'Send typing, recording, or paused presence in a chat',
				routing: { request: { method: 'POST', url: '/message/presence' } },
			},
			{
				name: 'Send Status',
				value: 'sendStatus',
				action: 'Send a status update',
				description: 'Send a status (story) update',
				routing: { request: { method: 'POST', url: '/send/status' } },
			},
			{
				name: 'Send Text',
				value: 'sendText',
				action: 'Send a text message',
				description: 'Send a plain text message',
				routing: { request: { method: 'POST', url: '/send/text' } },
			},
		],
	},

	// ============================================================
	// sendText
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		placeholder: '5511999999999',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendText'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		default: '',
		typeOptions: { rows: 4 },
		description: 'Message body to send',
		displayOptions: { show: { resource: ['message'], operation: ['sendText'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendText'] } },
	},
	{
		displayName: 'Link Preview Options',
		name: 'linkPreviewOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['sendText'] } },
		options: [
			{
				displayName: 'Enable Link Preview',
				name: 'linkPreview',
				type: 'boolean',
				default: false,
				description: 'Whether to generate a link preview for URLs in the text',
				routing: { send: { type: 'body', property: 'linkPreview' } },
			},
			{
				displayName: 'Link Preview Description',
				name: 'linkPreviewDescription',
				type: 'string',
				default: '',
				description: 'Custom description shown in the link preview',
				routing: { send: { type: 'body', property: 'linkPreviewDescription' } },
			},
			{
				displayName: 'Link Preview Image URL',
				name: 'linkPreviewImageURL',
				type: 'string',
				default: '',
				description: 'Custom image URL shown in the link preview',
				routing: { send: { type: 'body', property: 'linkPreviewImageURL' } },
			},
			{
				displayName: 'Link Preview Large Thumb',
				name: 'linkPreviewLargeThumb',
				type: 'boolean',
				default: false,
				description: 'Whether to render the preview thumbnail as large',
				routing: { send: { type: 'body', property: 'linkPreviewLargeThumb' } },
			},
			{
				displayName: 'Link Preview Title',
				name: 'linkPreviewTitle',
				type: 'string',
				default: '',
				description: 'Custom title shown in the link preview',
				routing: { send: { type: 'body', property: 'linkPreviewTitle' } },
			},
		],
	},

	// ============================================================
	// sendMedia
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		placeholder: '5511999999999',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Media Type',
		name: 'mediaType',
		type: 'options',
		required: true,
		default: 'image',
		description: 'Type of media to send',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
		options: [
			{ name: 'Audio', value: 'audio' },
			{ name: 'Document', value: 'document' },
			{ name: 'Image', value: 'image' },
			{ name: 'My Audio', value: 'myaudio' },
			{ name: 'PTT (Voice Note)', value: 'ptt' },
			{ name: 'PTV (Video Note)', value: 'ptv' },
			{ name: 'Sticker', value: 'sticker' },
			{ name: 'Video', value: 'video' },
		],
		routing: { send: { type: 'body', property: 'type' } },
	},
	{
		displayName: 'File',
		name: 'file',
		type: 'string',
		required: true,
		default: '',
		description: 'URL or base64 string of the media file',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
		routing: { send: { type: 'body', property: 'file' } },
	},
	{
		displayName: 'Caption Text',
		name: 'text',
		type: 'string',
		default: '',
		typeOptions: { rows: 3 },
		description: 'Optional caption to send with the media',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		displayName: 'Document Name',
		name: 'docName',
		type: 'string',
		default: '',
		description: 'File name to display when sending a document',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
		routing: { send: { type: 'body', property: 'docName' } },
	},
	{
		displayName: 'Mimetype',
		name: 'mimetype',
		type: 'string',
		default: '',
		description: 'MIME type override (e.g. application/pdf)',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
		routing: { send: { type: 'body', property: 'mimetype' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
	},

	// ============================================================
	// sendContact
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		required: true,
		default: '',
		description: 'Full name of the contact',
		displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } },
		routing: { send: { type: 'body', property: 'fullName' } },
	},
	{
		displayName: 'Phone Number',
		name: 'phoneNumber',
		type: 'string',
		required: true,
		default: '',
		description: 'Phone number of the contact in E.164 format',
		displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } },
		routing: { send: { type: 'body', property: 'phoneNumber' } },
	},
	{
		displayName: 'Organization',
		name: 'organization',
		type: 'string',
		default: '',
		description: 'Organization or company name',
		displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } },
		routing: { send: { type: 'body', property: 'organization' } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@email.com',
		default: '',
		description: 'Email address of the contact',
		displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } },
		routing: { send: { type: 'body', property: 'email' } },
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		default: '',
		description: 'Website URL of the contact',
		displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } },
		routing: { send: { type: 'body', property: 'url' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } },
	},

	// ============================================================
	// sendLocation
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		required: true,
		default: 0,
		description: 'Latitude in decimal degrees',
		displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } },
		routing: { send: { type: 'body', property: 'latitude' } },
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		required: true,
		default: 0,
		description: 'Longitude in decimal degrees',
		displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } },
		routing: { send: { type: 'body', property: 'longitude' } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		description: 'Name of the location',
		displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } },
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Address',
		name: 'address',
		type: 'string',
		default: '',
		description: 'Street address of the location',
		displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } },
		routing: { send: { type: 'body', property: 'address' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } },
	},

	// ============================================================
	// sendMenu
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Menu Type',
		name: 'menuType',
		type: 'options',
		required: true,
		default: 'button',
		description: 'Type of interactive menu',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		options: [
			{ name: 'Button', value: 'button' },
			{ name: 'Carousel', value: 'carousel' },
			{ name: 'List', value: 'list' },
			{ name: 'Poll', value: 'poll' },
		],
		routing: { send: { type: 'body', property: 'menuType' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		default: '',
		typeOptions: { rows: 4 },
		description: 'Main text/body of the menu message',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		displayName: 'Choices',
		name: 'choices',
		type: 'string',
		required: true,
		default: [],
		typeOptions: { multipleValues: true },
		description: 'List of choices for the menu (buttons, list items, poll options, or card titles)',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		routing: { send: { type: 'body', property: 'choices' } },
	},
	{
		displayName: 'Footer Text',
		name: 'footerText',
		type: 'string',
		default: '',
		description: 'Footer text shown below the menu',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		routing: { send: { type: 'body', property: 'footerText' } },
	},
	{
		displayName: 'List Button',
		name: 'listButton',
		type: 'string',
		default: '',
		description: 'Label for the button that opens the list (list menus only)',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		routing: { send: { type: 'body', property: 'listButton' } },
	},
	{
		displayName: 'Selectable Count',
		name: 'selectableCount',
		type: 'number',
		default: 0,
		description: 'Number of options the user can pick (poll menus)',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		routing: { send: { type: 'body', property: 'selectableCount' } },
	},
	{
		displayName: 'Image Button',
		name: 'imageButton',
		type: 'string',
		default: '',
		description: 'URL of an image to display above the button menu',
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
		routing: { send: { type: 'body', property: 'imageButton' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendMenu'] } },
	},

	// ============================================================
	// sendCarousel
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendCarousel'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		default: '',
		typeOptions: { rows: 3 },
		description: 'Header text shown above the carousel',
		displayOptions: { show: { resource: ['message'], operation: ['sendCarousel'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		displayName: 'Cards',
		name: 'carousel',
		type: 'fixedCollection',
		placeholder: 'Add Card',
		default: {},
		typeOptions: { multipleValues: true },
		displayOptions: { show: { resource: ['message'], operation: ['sendCarousel'] } },
		routing: { send: { type: 'body', property: 'carousel' } },
		options: [
			{
				name: 'cards',
				displayName: 'Card',
				values: [
					{
						displayName: 'Text',
						name: 'text',
						type: 'string',
						default: '',
						typeOptions: { rows: 2 },
						description: 'Body text of the card',
					},
					{
						displayName: 'File',
						name: 'file',
						type: 'string',
						default: '',
						description: 'URL or base64 of the card image',
					},
					{
						displayName: 'Buttons',
						name: 'buttons',
						type: 'string',
						default: [],
						typeOptions: { multipleValues: true },
						description: 'Button labels for the card',
					},
				],
			},
		],
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendCarousel'] } },
	},

	// ============================================================
	// sendLocationRequest
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendLocationRequest'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		default: '',
		typeOptions: { rows: 3 },
		description: 'Message body shown with the location-request button',
		displayOptions: { show: { resource: ['message'], operation: ['sendLocationRequest'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendLocationRequest'] } },
	},

	// ============================================================
	// sendPaymentRequest
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		required: true,
		default: 0,
		description: 'Payment amount in the local currency',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'amount' } },
	},
	{
		displayName: 'PIX Key',
		name: 'pixKey',
		type: 'string',
		default: '',
		description: 'PIX key used for the payment',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'pixKey' } },
	},
	{
		displayName: 'PIX Type',
		name: 'pixType',
		type: 'options',
		default: 'cpf',
		description: 'Type of the PIX key',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		options: [
			{ name: 'CNPJ', value: 'cnpj' },
			{ name: 'CPF', value: 'cpf' },
			{ name: 'Email', value: 'email' },
			{ name: 'EVP (Random)', value: 'evp' },
			{ name: 'Phone', value: 'phone' },
		],
		routing: { send: { type: 'body', property: 'pixType' } },
	},
	{
		displayName: 'PIX Name',
		name: 'pixName',
		type: 'string',
		default: '',
		description: 'Account holder name shown on the payment request',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'pixName' } },
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		description: 'Title shown on the payment request',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'title' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		default: '',
		typeOptions: { rows: 3 },
		description: 'Description shown with the payment request',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		displayName: 'Footer',
		name: 'footer',
		type: 'string',
		default: '',
		description: 'Footer text shown on the payment request',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'footer' } },
	},
	{
		displayName: 'Payment Link',
		name: 'paymentLink',
		type: 'string',
		default: '',
		description: 'External payment link to attach',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'paymentLink' } },
	},
	{
		displayName: 'Boleto Code',
		name: 'boletoCode',
		type: 'string',
		default: '',
		description: 'Boleto digitable line / barcode',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'boletoCode' } },
	},
	{
		displayName: 'File URL',
		name: 'fileUrl',
		type: 'string',
		default: '',
		description: 'URL of a related file (PDF of the boleto, etc.)',
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
		routing: { send: { type: 'body', property: 'fileUrl' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendPaymentRequest'] } },
	},

	// ============================================================
	// sendPixButton
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendPixButton'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'PIX Type',
		name: 'pixType',
		type: 'options',
		required: true,
		default: 'cpf',
		description: 'Type of the PIX key',
		displayOptions: { show: { resource: ['message'], operation: ['sendPixButton'] } },
		options: [
			{ name: 'CNPJ', value: 'cnpj' },
			{ name: 'CPF', value: 'cpf' },
			{ name: 'Email', value: 'email' },
			{ name: 'EVP (Random)', value: 'evp' },
			{ name: 'Phone', value: 'phone' },
		],
		routing: { send: { type: 'body', property: 'pixType' } },
	},
	{
		displayName: 'PIX Key',
		name: 'pixKey',
		type: 'string',
		required: true,
		default: '',
		description: 'PIX key value',
		displayOptions: { show: { resource: ['message'], operation: ['sendPixButton'] } },
		routing: { send: { type: 'body', property: 'pixKey' } },
	},
	{
		displayName: 'PIX Name',
		name: 'pixName',
		type: 'string',
		default: '',
		description: 'Account holder name shown with the PIX button',
		displayOptions: { show: { resource: ['message'], operation: ['sendPixButton'] } },
		routing: { send: { type: 'body', property: 'pixName' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendPixButton'] } },
	},

	// ============================================================
	// sendStatus
	// ============================================================
	{
		displayName: 'Status Type',
		name: 'statusType',
		type: 'options',
		required: true,
		default: 'text',
		description: 'Type of status to publish',
		displayOptions: { show: { resource: ['message'], operation: ['sendStatus'] } },
		options: [
			{ name: 'Audio', value: 'audio' },
			{ name: 'Image', value: 'image' },
			{ name: 'Text', value: 'text' },
			{ name: 'Video', value: 'video' },
		],
		routing: { send: { type: 'body', property: 'type' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		default: '',
		typeOptions: { rows: 3 },
		description: 'Text content of the status',
		displayOptions: { show: { resource: ['message'], operation: ['sendStatus'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},
	{
		displayName: 'File',
		name: 'file',
		type: 'string',
		default: '',
		description: 'URL or base64 of the media file (for image/video/audio statuses)',
		displayOptions: { show: { resource: ['message'], operation: ['sendStatus'] } },
		routing: { send: { type: 'body', property: 'file' } },
	},
	{
		displayName: 'Background Color',
		name: 'background_color',
		type: 'color',
		default: '',
		description: 'Background color (hex) for text statuses',
		displayOptions: { show: { resource: ['message'], operation: ['sendStatus'] } },
		routing: { send: { type: 'body', property: 'background_color' } },
	},
	{
		displayName: 'Font',
		name: 'font',
		type: 'number',
		default: 0,
		description: 'Font index for text statuses',
		displayOptions: { show: { resource: ['message'], operation: ['sendStatus'] } },
		routing: { send: { type: 'body', property: 'font' } },
	},
	{
		...sendAdditionalFields,
		displayOptions: { show: { resource: ['message'], operation: ['sendStatus'] } },
	},

	// ============================================================
	// sendPresenceInChat
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Chat phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['sendPresenceInChat'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Presence',
		name: 'presence',
		type: 'options',
		required: true,
		default: 'composing',
		description: 'Presence state to broadcast in the chat',
		displayOptions: { show: { resource: ['message'], operation: ['sendPresenceInChat'] } },
		options: [
			{ name: 'Composing (Typing)', value: 'composing' },
			{ name: 'Paused', value: 'paused' },
			{ name: 'Recording', value: 'recording' },
		],
		routing: { send: { type: 'body', property: 'presence' } },
	},
	{
		displayName: 'Delay (Ms)',
		name: 'delay',
		type: 'number',
		default: 0,
		description: 'Duration to keep the presence active, in milliseconds',
		displayOptions: { show: { resource: ['message'], operation: ['sendPresenceInChat'] } },
		routing: { send: { type: 'body', property: 'delay' } },
	},

	// ============================================================
	// react
	// ============================================================
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		required: true,
		default: '',
		description: 'Chat phone number in E.164 format (or group JID)',
		displayOptions: { show: { resource: ['message'], operation: ['react'] } },
		routing: { send: { type: 'body', property: 'number' } },
	},
	{
		displayName: 'Message ID',
		name: 'id',
		type: 'string',
		required: true,
		default: '',
		description: 'ID of the message to react to',
		displayOptions: { show: { resource: ['message'], operation: ['react'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		default: '',
		description: 'Emoji used as the reaction (empty string removes the reaction)',
		displayOptions: { show: { resource: ['message'], operation: ['react'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},

	// ============================================================
	// edit
	// ============================================================
	{
		displayName: 'Message ID',
		name: 'id',
		type: 'string',
		required: true,
		default: '',
		description: 'ID of the message to edit',
		displayOptions: { show: { resource: ['message'], operation: ['edit'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		default: '',
		typeOptions: { rows: 4 },
		description: 'New text content of the message',
		displayOptions: { show: { resource: ['message'], operation: ['edit'] } },
		routing: { send: { type: 'body', property: 'text' } },
	},

	// ============================================================
	// delete
	// ============================================================
	{
		displayName: 'Message ID',
		name: 'id',
		type: 'string',
		required: true,
		default: '',
		description: 'ID of the message to delete',
		displayOptions: { show: { resource: ['message'], operation: ['delete'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},

	// ============================================================
	// markAsRead
	// ============================================================
	{
		displayName: 'Message IDs',
		name: 'id',
		type: 'string',
		required: true,
		default: [],
		typeOptions: { multipleValues: true },
		description: 'List of message IDs to mark as read',
		displayOptions: { show: { resource: ['message'], operation: ['markAsRead'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},

	// ============================================================
	// find
	// ============================================================
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['find'] } },
		options: [
			{
				displayName: 'Chat ID',
				name: 'chatid',
				type: 'string',
				default: '',
				description: 'Restrict search to a specific chat',
				routing: { send: { type: 'body', property: 'chatid' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: {
					minValue: 1,
				},
				default: 50,
				description: 'Max number of results to return',
				routing: { send: { type: 'body', property: 'limit' } },
			},
			{
				displayName: 'Message ID',
				name: 'id',
				type: 'string',
				default: '',
				description: 'Specific message ID to look up',
				routing: { send: { type: 'body', property: 'id' } },
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				description: 'Result offset for pagination',
				routing: { send: { type: 'body', property: 'offset' } },
			},
			{
				displayName: 'Track ID',
				name: 'track_id',
				type: 'string',
				default: '',
				description: 'Filter by tracking ID',
				routing: { send: { type: 'body', property: 'track_id' } },
			},
			{
				displayName: 'Track Source',
				name: 'track_source',
				type: 'string',
				default: '',
				description: 'Filter by tracking source',
				routing: { send: { type: 'body', property: 'track_source' } },
			},
		],
	},

	// ============================================================
	// download
	// ============================================================
	{
		displayName: 'Message ID',
		name: 'id',
		type: 'string',
		required: true,
		default: '',
		description: 'ID of the message whose media should be downloaded',
		displayOptions: { show: { resource: ['message'], operation: ['download'] } },
		routing: { send: { type: 'body', property: 'id' } },
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['download'] } },
		options: [
			{
				displayName: 'Download Quoted',
				name: 'download_quoted',
				type: 'boolean',
				default: false,
				description: 'Whether to download the media from a quoted message instead',
				routing: { send: { type: 'body', property: 'download_quoted' } },
			},
			{
				displayName: 'Generate MP3',
				name: 'generate_mp3',
				type: 'boolean',
				default: false,
				description: 'Whether to convert audio to MP3 in the response',
				routing: { send: { type: 'body', property: 'generate_mp3' } },
			},
			{
				displayName: 'OpenAI API Key',
				name: 'openai_apikey',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'OpenAI API key used when transcribing audio',
				routing: { send: { type: 'body', property: 'openai_apikey' } },
			},
			{
				displayName: 'Return Base64',
				name: 'return_base64',
				type: 'boolean',
				default: false,
				description: 'Whether to return the file as a base64 string',
				routing: { send: { type: 'body', property: 'return_base64' } },
			},
			{
				displayName: 'Return Link',
				name: 'return_link',
				type: 'boolean',
				default: false,
				description: 'Whether to return a hosted link to the file',
				routing: { send: { type: 'body', property: 'return_link' } },
			},
			{
				displayName: 'Transcribe',
				name: 'transcribe',
				type: 'boolean',
				default: false,
				description: 'Whether to transcribe audio content using OpenAI',
				routing: { send: { type: 'body', property: 'transcribe' } },
			},
		],
	},
];
